In [2]:
# Importing Libraries
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
# loading the data from the csv file to apandas dataframe
movies_data = pd.read_csv('C:/Users/Dell/Downloads/movies.csv') 
# printing the first 5 rows of the dataframe
movies_data.head()


budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   10-12-2009  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   19-05-2007   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   26-10-2015   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   16-07-2012  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   07-03-2012   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [4]:
# number of rows and columns in the data frame
movies_data.shape

(4803, 20)

In [5]:
# selecting the relevant features for recommendation
selected_features = ['genres','keywords','tagline']
print(selected_features)


['genres', 'keywords', 'tagline']


In [6]:
# replacing the null valuess with null string
for feature in selected_features:
 movies_data[feature] = movies_data[feature].fillna('')


In [7]:
# combining all the 3 selected features
combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']
print(combined_features)


0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...                        
4798    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801                       [] [] A New Yorker in Shanghai
4802    [{"id": 99, "name": "Documentary"}] [{"id": 15...
Length: 4803, dtype: object


In [8]:
# converting the text data to feature vectors
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)


  (0, 15819)	0.13067136923706554
  (0, 15624)	0.042190581271209615
  (0, 19186)	0.06115902867437435
  (0, 18220)	0.034745900795906386
  (0, 12609)	0.11947677021689071
  (0, 7811)	0.07852455953648513
  (0, 5739)	0.07884757815388245
  (0, 17579)	0.09812989462371097
  (0, 10170)	0.051270797096986086
  (0, 15131)	0.09231570917121786
  (0, 5458)	0.12412294859965346
  (0, 16644)	0.11947677021689071
  (0, 16234)	0.08169455710568298
  (0, 5012)	0.13067136923706554
  (0, 10213)	0.09308492085598188
  (0, 2739)	0.1353175476198283
  (0, 10026)	0.0943121230774711
  (0, 14774)	0.054074000786992364
  (0, 1066)	0.13067136923706554
  (0, 10569)	0.08003190699608953
  (0, 1030)	0.09708757217654103
  (0, 17539)	0.08614731530249232
  (0, 836)	0.09348371624094821
  (0, 14915)	0.0915814739862989
  (0, 499)	0.13067136923706554
  :	:
  (4800, 18126)	0.1829383057392132
  (4800, 12381)	0.05454819765741068
  (4800, 4006)	0.054671196139331954
  (4800, 10373)	0.1549226921988739
  (4800, 14774)	0.10535660066722898
 

In [9]:
# getting the similarity scores using cosine similarity
similarity = cosine_similarity(feature_vectors)
print(similarity)
print(similarity.shape)


[[1.         0.33622781 0.26096609 ... 0.26614764 0.         0.18793274]
 [0.33622781 1.         0.25454511 ... 0.25652912 0.         0.17182781]
 [0.26096609 0.25454511 1.         ... 0.19299489 0.         0.14120104]
 ...
 [0.26614764 0.25652912 0.19299489 ... 1.         0.         0.14646562]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.18793274 0.17182781 0.14120104 ... 0.14646562 0.         1.        ]]
(4803, 4803)


In [10]:
# getting the movie name from the user
movie_name = input(' Enter your favourite movie name : ')



 Enter your favourite movie name : Iron man


In [11]:
# creating a list with all the movie names given in the dataset
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [12]:
# finding the close match for the movie name given by the user
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)
close_match = find_close_match[0]
print(close_match)


['Iron Man', 'Iron Man 3', 'Iron Man 2']
Iron Man


In [13]:
# finding the index of the movie with title
index_of_the_movie = movies_data[movies_data.title == 
close_match].index.values[0]
print(index_of_the_movie)

68


In [14]:
# getting a list of similar movies
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)
len(similarity_score)


[(0, 0.268245529904998), (1, 0.27230539512799146), (2, 0.23025687903691588), (3, 0.2855862989782413), (4, 0.2452709797905724), (5, 0.334782393750383), (6, 0.2301139046183327), (7, 0.5461194888991008), (8, 0.19920648063324925), (9, 0.30092250315783897), (10, 0.33544694732525276), (11, 0.1980719821257449), (12, 0.2678929261311803), (13, 0.20243244759572993), (14, 0.34282753168585234), (15, 0.22852000842896214), (16, 0.5328165870806456), (17, 0.26420396941902446), (18, 0.19995132986203912), (19, 0.2278015922764574), (20, 0.27955791218591625), (21, 0.17214861539084014), (22, 0.15773107361151067), (23, 0.18185021332657014), (24, 0.20662855230506988), (25, 0.234156732889537), (26, 0.5516559208699451), (27, 0.2559235310111847), (28, 0.24641357129695407), (29, 0.22457582845778898), (30, 0.340588852516945), (31, 0.6280356282821119), (32, 0.20942440781965987), (33, 0.4384804700853492), (34, 0.19293531200827974), (35, 0.2448275702227959), (36, 0.2046526072651636), (37, 0.20328704857765426), (38, 

4803

In [15]:
# sorting the movies based on their similarity score
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse 
= True) 
print(sorted_similar_movies)

[(68, 1.0), (31, 0.6280356282821119), (79, 0.6034456313868325), (182, 0.602968090041831), (26, 0.5516559208699451), (7, 0.5461194888991008), (85, 0.5407399963016103), (16, 0.5328165870806456), (169, 0.49906653979457405), (174, 0.49266688638893086), (126, 0.48735008293016), (511, 0.4768029635667649), (94, 0.4616968934339485), (129, 0.4562188550026674), (122, 0.439741570761005), (33, 0.4384804700853492), (203, 0.42671384479101176), (232, 0.41351989093153335), (788, 0.41057095525706166), (64, 0.40719857674350346), (242, 0.4008507358611254), (46, 0.3883050577936155), (1740, 0.3859995579228917), (101, 0.3785266947594348), (215, 0.3720567925963767), (38, 0.36474174528048653), (4033, 0.3622137671370895), (2390, 0.36126061733073), (1192, 0.3564756178698613), (238, 0.35541702385380275), (2442, 0.3553198847037723), (4487, 0.35157858820993704), (3993, 0.3498901008725036), (618, 0.34908878398372256), (813, 0.347658786633614), (3437, 0.3459660815247876), (165, 0.3450281735782724), (14, 0.3428275316

In [16]:
# print the name of similar movies based on the index
print('Movies suggested for you : \n')
i = 1
for movie in sorted_similar_movies:
 index = movie[0]
 title_from_index = movies_data[movies_data.index==index]['title'].values[0]
 if (i<30):
  print(i, '.',title_from_index)
  i+=1


Movies suggested for you : 

1 . Iron Man
2 . Iron Man 3
3 . Iron Man 2
4 . Ant-Man
5 . Captain America: Civil War
6 . Avengers: Age of Ultron
7 . Captain America: The Winter Soldier
8 . The Avengers
9 . Captain America: The First Avenger
10 . The Incredible Hulk
11 . Thor: The Dark World
12 . X-Men
13 . Guardians of the Galaxy
14 . Thor
15 . X-Men Origins: Wolverine
16 . X-Men: The Last Stand
17 . X2
18 . The Wolverine
19 . Deadpool
20 . X-Men: Apocalypse
21 . Fantastic Four
22 . X-Men: Days of Future Past
23 . Kick-Ass 2
24 . X-Men: First Class
25 . Fantastic 4: Rise of the Silver Surfer
26 . The Amazing Spider-Man 2
27 . Super
28 . Red Sonja
29 . Spawn


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Load dataset
#data = pd.read_csv('C:/Users/Dell/Downloads/data.csv')

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data.drop('label', axis=1), 
                                                    data['vote_average'], 
                                                    test_size=0.3, 
                                                    random_state=42)

# Train model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)